removing install requirements
`python ./setup.py install` in Python 2.7.12, Windows 10 throws this error

`Traceback (most recent call last):
  File "./setup.py", line 9, in <module>
    reqs = [str(ir.req) for ir in install_reqs]
  File "C:\Python27\lib\site-packages\pip\req\req_file.py", line 79, in parse_requirements
    "parse_requirements() missing 1 required keyword argument: "
TypeError: parse_requirements() missing 1 required keyword argument: 'session'`

removing the install requirements fixed it